### PR TITLE
Running uniq on all joins before returning them.

### PR DESCRIPTION
**Pull request by russ**
This avoids the issue where join gets called multiple times with the
same arguments.

## Description
Making sure that only uniq joins are ran.

## Motivation and Context
In a more complicated setup, I don't really know if an association has been called before. This change allows join to be called multiple times with the same arguments without fear of postgres getting duplicate join errors.

## How Has This Been Tested?
Locally, no specs were added.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by russ** [comment]
I'm running into unintended issues in production from this change. Seems like it's a bit more complex than I originally thought.

**Comment by russ** [comment]
Closing this out.

**Comment by anykeyh** [comment]
What are the problem you face with this change? Would be happy to help 😄

**Comment by russ** [comment]
I'm hoping to find some time soon where I can replicate the issue in Rails. I'm not sure if Rails would handle this case in the same way or not.

**Pull request closed without merging**
